# Generated by Django 6.0.1 on 2026-05-15 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa grupy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to='volunteers.volunteer', verbose_name='Lider grupy')),
            ],
            options={
                'verbose_name': 'Grupa',
                'verbose_name_plural': 'Grupy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data przypisania')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_assignments', to='beneficiaries.beneficiary', verbose_name='Podopieczny')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_assignments', to='volunteers.volunteer', verbose_name='Wolontariusz')),
            ],
            options={
                'verbose_name': 'Przypisanie',
                'verbose_name_plural': 'Przypisania',
                'ordering': ['beneficiary__full_name'],
                'unique_together': {('beneficiary', 'volunteer')},
            },
        ),
    ]
