# Generated by Django 6.0.1 on 2026-05-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='assigned_groups', to='volunteers.volunteer', verbose_name='Wolontariusze w grupie'),
        ),
    ]
