# Generated by Django 6.0.1 on 2026-06-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_volunteers'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryassignment',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Główny wolontariusz'),
        ),
    ]
