# Generated by Django 6.0.1 on 2026-06-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_beneficiaryassignment_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryassignment',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Bieżące informacje'),
        ),
    ]
