# Generated by Django 6.0.1 on 2026-05-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Imię i Nazwisko')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('social_link', models.URLField(blank=True, null=True, verbose_name='Link do profilu społecznościowego')),
                ('status', models.CharField(choices=[('Aktywny', 'Aktywny'), ('Były', 'Były')], default='Aktywny', max_length=20, verbose_name='Status')),
                ('join_date', models.DateField(verbose_name='Data przystąpienia')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('history', models.TextField(blank=True, verbose_name='Historia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Wolontariusz',
                'verbose_name_plural': 'Wolontariusze',
                'ordering': ['full_name'],
            },
        ),
    ]
