# Generated by Django 6.0.1 on 2026-05-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Imię i Nazwisko')),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon podopiecznego')),
                ('family_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon rodziny/opiekuna')),
                ('description', models.TextField(blank=True, verbose_name='Opis podopiecznego')),
                ('status', models.CharField(choices=[('OBECNY', 'Obecny'), ('ZMARŁY', 'Zmarły'), ('BYŁY', 'Były'), ('DPS_ZOL', 'DPS/ZOL')], default='OBECNY', max_length=20, verbose_name='Status')),
                ('bo_enrolled', models.BooleanField(default=False, verbose_name='Uczestnik BO')),
                ('last_priest_visit', models.DateField(blank=True, null=True, verbose_name='Data ostatnich odwiedzin księdza')),
                ('last_volunteer_meeting', models.DateField(blank=True, null=True, verbose_name='Termin ostatniego spotkania z wolontariuszami')),
                ('history', models.TextField(blank=True, verbose_name='Historia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Podopieczny',
                'verbose_name_plural': 'Podopieczni',
                'ordering': ['full_name'],
            },
        ),
    ]
