"""PAP-98 production baseline

Revision ID: pap98_baseline
Revises:
Create Date: 2026-07-13 19:39:56.413183+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "pap98_baseline"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("actor_display_name", sa.String(length=255), nullable=True),
        sa.Column("context_type", sa.String(length=100), nullable=True),
        sa.Column("context_id", sa.String(length=255), nullable=True),
        sa.Column(
            "changes",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", "created_at"),
        postgresql_partition_by="RANGE (created_at)",
    )
    op.create_index(
        "idx_audit_actor",
        "audit_events",
        ["actor_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_audit_changes_gin",
        "audit_events",
        ["changes"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_audit_context",
        "audit_events",
        ["context_type", "context_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_audit_entity",
        "audit_events",
        ["entity_type", "entity_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "CREATE TABLE audit_events_default PARTITION OF audit_events DEFAULT"
        )
        op.execute(
            """
            CREATE FUNCTION prevent_audit_event_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit_events is append-only';
            END;
            $$ LANGUAGE plpgsql
            """
        )
        op.execute(
            """
            CREATE TRIGGER audit_events_append_only
            BEFORE UPDATE OR DELETE ON audit_events
            FOR EACH ROW EXECUTE FUNCTION prevent_audit_event_mutation()
            """
        )
        op.execute(
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM pg_roles WHERE rolname = 'fastapi_db_user'
                ) THEN
                    REVOKE UPDATE, DELETE ON audit_events FROM fastapi_db_user;
                END IF;
            END
            $$
            """
        )
    op.create_table(
        "beneficiary_recruitment_fields",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=250), nullable=False),
        sa.Column("field_type", sa.String(length=30), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("placeholder", sa.String(length=250), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_beneficiary_recruitment_fields_key"),
        "beneficiary_recruitment_fields",
        ["key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_beneficiary_recruitment_fields_position"),
        "beneficiary_recruitment_fields",
        ["position"],
        unique=False,
    )
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("system_key", sa.String(length=50), nullable=True),
        sa.Column("icon", sa.String(length=16), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_departments_name"), "departments", ["name"], unique=True)
    op.create_index(
        op.f("ix_departments_system_key"), "departments", ["system_key"], unique=True
    )
    op.create_table(
        "departure_fields",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=250), nullable=False),
        sa.Column("field_type", sa.String(length=30), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("placeholder", sa.String(length=250), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_departure_fields_key"), "departure_fields", ["key"], unique=True
    )
    op.create_index(
        op.f("ix_departure_fields_position"),
        "departure_fields",
        ["position"],
        unique=False,
    )
    op.create_table(
        "functions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("system_key", sa.String(length=50), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_functions_name"), "functions", ["name"], unique=True)
    op.create_index(
        op.f("ix_functions_system_key"), "functions", ["system_key"], unique=True
    )
    op.create_table(
        "recruitment_fields",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=250), nullable=False),
        sa.Column("field_type", sa.String(length=30), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("placeholder", sa.String(length=250), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recruitment_fields_key"), "recruitment_fields", ["key"], unique=True
    )
    op.create_index(
        op.f("ix_recruitment_fields_position"),
        "recruitment_fields",
        ["position"],
        unique=False,
    )
    op.create_table(
        "security_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("system_key", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_security_groups_name"), "security_groups", ["name"], unique=True
    )
    op.create_index(
        op.f("ix_security_groups_system_key"),
        "security_groups",
        ["system_key"],
        unique=True,
    )
    op.create_table(
        "security_permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_security_permissions_category"),
        "security_permissions",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_permissions_code"),
        "security_permissions",
        ["code"],
        unique=True,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=150), nullable=False),
        sa.Column("last_name", sa.String(length=150), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "volunteers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("social_link", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("join_date", sa.DateTime(), nullable=False),
        sa.Column("notes", sa.String(), nullable=False),
        sa.Column("history", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_volunteers_email"), "volunteers", ["email"], unique=True)
    op.create_index(
        op.f("ix_volunteers_full_name"), "volunteers", ["full_name"], unique=False
    )
    op.create_table(
        "bug_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("resolution_comment", sa.String(), nullable=False),
        sa.Column("reporter_id", sa.Integer(), nullable=True),
        sa.Column("reporter_email", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("storage_backend", sa.String(length=50), nullable=True),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("content_type", sa.String(length=127), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["reporter_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_bug_reports_reporter_id"), "bug_reports", ["reporter_id"], unique=False
    )
    op.create_index(
        op.f("ix_bug_reports_status"), "bug_reports", ["status"], unique=False
    )
    op.create_table(
        "calendar_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("is_all_day", sa.Boolean(), nullable=False),
        sa.Column("location", sa.String(length=300), nullable=False),
        sa.Column("recurrence_rule", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("visibility", sa.String(length=30), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'cancelled')",
            name="ck_calendar_event_status",
        ),
        sa.CheckConstraint(
            "visibility IN ('organization', 'admins')",
            name="ck_calendar_event_visibility",
        ),
        sa.CheckConstraint("ends_at >= starts_at", name="ck_calendar_event_dates"),
        sa.CheckConstraint("sequence >= 0", name="ck_calendar_event_sequence"),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uid"),
    )
    op.create_index(
        op.f("ix_calendar_events_author_id"),
        "calendar_events",
        ["author_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_calendar_events_status"), "calendar_events", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_calendar_events_title"), "calendar_events", ["title"], unique=False
    )
    op.create_index(
        op.f("ix_calendar_events_visibility"),
        "calendar_events",
        ["visibility"],
        unique=False,
    )
    op.create_table(
        "calendar_feed_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "department_inventory_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("location", sa.String(length=300), nullable=False),
        sa.Column("borrowed_by_volunteer_id", sa.Integer(), nullable=True),
        sa.Column("borrowed_at", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["borrowed_by_volunteer_id"], ["volunteers.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_department_inventory_items_borrowed_by_volunteer_id"),
        "department_inventory_items",
        ["borrowed_by_volunteer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_department_inventory_items_department_id"),
        "department_inventory_items",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_department_inventory_items_name"),
        "department_inventory_items",
        ["name"],
        unique=False,
    )
    op.create_table(
        "department_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("volunteer_id", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="ACTIVE", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["volunteer_id"], ["volunteers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "department_id", "volunteer_id", name="uq_department_volunteer"
        ),
    )
    op.create_index(
        op.f("ix_department_members_department_id"),
        "department_members",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_department_members_volunteer_id"),
        "department_members",
        ["volunteer_id"],
        unique=False,
    )
    op.create_table(
        "departure_interviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("volunteer_id", sa.Integer(), nullable=False),
        sa.Column("departure_date", sa.Date(), nullable=False),
        sa.Column("departure_reason", sa.Text(), nullable=False),
        sa.Column("stay_in_contact", sa.Boolean(), nullable=False),
        sa.Column("answers", sa.JSON(), nullable=False),
        sa.Column("completed_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["completed_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["volunteer_id"], ["volunteers.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_departure_interviews_departure_date"),
        "departure_interviews",
        ["departure_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_departure_interviews_volunteer_id"),
        "departure_interviews",
        ["volunteer_id"],
        unique=True,
    )
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("system_key", sa.String(length=50), nullable=True),
        sa.Column("leader_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["leader_id"], ["volunteers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_groups_name"), "groups", ["name"], unique=False)
    op.create_index(op.f("ix_groups_system_key"), "groups", ["system_key"], unique=True)
    op.create_table(
        "recruitment_submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("social_link", sa.String(length=500), nullable=False),
        sa.Column("availability", sa.Text(), nullable=False),
        sa.Column("answers", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("return_reason", sa.Text(), nullable=True),
        sa.Column("decision_comment", sa.Text(), nullable=True),
        sa.Column("volunteer_id", sa.Integer(), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status_changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["volunteer_id"], ["volunteers.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("volunteer_id"),
    )
    op.create_index(
        op.f("ix_recruitment_submissions_email"),
        "recruitment_submissions",
        ["email"],
        unique=True,
    )
    op.create_index(
        op.f("ix_recruitment_submissions_full_name"),
        "recruitment_submissions",
        ["full_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recruitment_submissions_status"),
        "recruitment_submissions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recruitment_submissions_user_id"),
        "recruitment_submissions",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "security_group_permissions",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["security_groups.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["security_permissions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("group_id", "permission_id"),
    )
    op.create_table(
        "security_user_groups",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["security_groups.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "group_id"),
    )
    op.create_table(
        "volunteer_function",
        sa.Column("volunteer_id", sa.Integer(), nullable=False),
        sa.Column("function_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["function_id"], ["functions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["volunteer_id"], ["volunteers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("volunteer_id", "function_id"),
    )
    op.create_table(
        "beneficiaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("family_phone", sa.String(length=20), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("bo_enrolled", sa.Boolean(), nullable=False),
        sa.Column("last_priest_visit", sa.Date(), nullable=True),
        sa.Column("last_volunteer_meeting", sa.Date(), nullable=True),
        sa.Column("history", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_beneficiaries_full_name"), "beneficiaries", ["full_name"], unique=False
    )
    op.create_table(
        "calendar_audit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("changes", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["event_id"], ["calendar_events.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calendar_audit_action"), "calendar_audit", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_calendar_audit_actor_id"), "calendar_audit", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_calendar_audit_event_id"), "calendar_audit", ["event_id"], unique=False
    )
    op.create_table(
        "group_volunteer",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("volunteer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["volunteer_id"], ["volunteers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("group_id", "volunteer_id"),
    )
    op.create_table(
        "recruitment_onboarding_meetings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("meeting_type", sa.String(length=30), nullable=False),
        sa.Column("attended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "meeting_type IN ('CHARISM', 'COMMUNITY', 'ADMINISTRATION', 'ACTIVITY')",
            name="ck_recruitment_onboarding_meeting_type",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["recruitment_submissions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "submission_id",
            "meeting_type",
            name="uq_recruitment_onboarding_meeting_type",
        ),
    )
    op.create_index(
        op.f("ix_recruitment_onboarding_meetings_submission_id"),
        "recruitment_onboarding_meetings",
        ["submission_id"],
        unique=False,
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("status_is_manual", sa.Boolean(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["calendar_events.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tasks_department_id"), "tasks", ["department_id"], unique=False
    )
    op.create_index(op.f("ix_tasks_event_id"), "tasks", ["event_id"], unique=False)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_table(
        "attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("context", sa.String(length=50), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("beneficiary_id", sa.Integer(), nullable=True),
        sa.Column("volunteer_id", sa.Integer(), nullable=True),
        sa.Column("period", sa.String(length=7), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_backend", sa.String(length=50), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=127), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_by_username", sa.String(length=150), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_username", sa.String(length=150), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["beneficiary_id"], ["beneficiaries.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["volunteer_id"], ["volunteers.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attachments_beneficiary_id"),
        "attachments",
        ["beneficiary_id"],
        unique=False,
    )
    op.create_index(
        "ix_attachments_bo_card_lookup",
        "attachments",
        ["context", "group_id", "beneficiary_id", "volunteer_id", "period"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attachments_context"), "attachments", ["context"], unique=False
    )
    op.create_index(
        op.f("ix_attachments_group_id"), "attachments", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_attachments_period"), "attachments", ["period"], unique=False
    )
    op.create_index(
        op.f("ix_attachments_storage_key"), "attachments", ["storage_key"], unique=True
    )
    op.create_index(
        op.f("ix_attachments_volunteer_id"),
        "attachments",
        ["volunteer_id"],
        unique=False,
    )
    op.create_table(
        "beneficiary_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("beneficiary_id", sa.Integer(), nullable=False),
        sa.Column("volunteer_id", sa.Integer(), nullable=False),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.Column("additional_info", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["beneficiary_id"], ["beneficiaries.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["volunteer_id"], ["volunteers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "beneficiary_id", "volunteer_id", name="uq_beneficiary_volunteer"
        ),
    )
    op.create_table(
        "beneficiary_recruitment_submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("reporter_name", sa.String(length=200), nullable=False),
        sa.Column("reporter_phone", sa.String(length=20), nullable=False),
        sa.Column("help_needed", sa.Text(), nullable=False),
        sa.Column("answers", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("decision_comment", sa.Text(), nullable=True),
        sa.Column("beneficiary_id", sa.Integer(), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["beneficiary_id"], ["beneficiaries.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("beneficiary_id"),
    )
    op.create_index(
        op.f("ix_beneficiary_recruitment_submissions_full_name"),
        "beneficiary_recruitment_submissions",
        ["full_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_beneficiary_recruitment_submissions_status"),
        "beneficiary_recruitment_submissions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "task_assignees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("volunteer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["volunteer_id"], ["volunteers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "volunteer_id", name="uq_task_volunteer"),
    )
    op.create_index(
        op.f("ix_task_assignees_task_id"), "task_assignees", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_assignees_volunteer_id"),
        "task_assignees",
        ["volunteer_id"],
        unique=False,
    )
    op.create_table(
        "task_checklist_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("volunteer_id", sa.Integer(), nullable=True),
        sa.Column("is_done", sa.Boolean(), nullable=False),
        sa.Column("done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["volunteer_id"], ["volunteers.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_checklist_items_task_id"),
        "task_checklist_items",
        ["task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_checklist_items_volunteer_id"),
        "task_checklist_items",
        ["volunteer_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_task_checklist_items_volunteer_id"), table_name="task_checklist_items"
    )
    op.drop_index(
        op.f("ix_task_checklist_items_task_id"), table_name="task_checklist_items"
    )
    op.drop_table("task_checklist_items")
    op.drop_index(op.f("ix_task_assignees_volunteer_id"), table_name="task_assignees")
    op.drop_index(op.f("ix_task_assignees_task_id"), table_name="task_assignees")
    op.drop_table("task_assignees")
    op.drop_index(
        op.f("ix_beneficiary_recruitment_submissions_status"),
        table_name="beneficiary_recruitment_submissions",
    )
    op.drop_index(
        op.f("ix_beneficiary_recruitment_submissions_full_name"),
        table_name="beneficiary_recruitment_submissions",
    )
    op.drop_table("beneficiary_recruitment_submissions")
    op.drop_table("beneficiary_assignments")
    op.drop_index(op.f("ix_attachments_volunteer_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_storage_key"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_period"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_group_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_context"), table_name="attachments")
    op.drop_index("ix_attachments_bo_card_lookup", table_name="attachments")
    op.drop_index(op.f("ix_attachments_beneficiary_id"), table_name="attachments")
    op.drop_table("attachments")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_event_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_department_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(
        op.f("ix_recruitment_onboarding_meetings_submission_id"),
        table_name="recruitment_onboarding_meetings",
    )
    op.drop_table("recruitment_onboarding_meetings")
    op.drop_table("group_volunteer")
    op.drop_index(op.f("ix_calendar_audit_event_id"), table_name="calendar_audit")
    op.drop_index(op.f("ix_calendar_audit_actor_id"), table_name="calendar_audit")
    op.drop_index(op.f("ix_calendar_audit_action"), table_name="calendar_audit")
    op.drop_table("calendar_audit")
    op.drop_index(op.f("ix_beneficiaries_full_name"), table_name="beneficiaries")
    op.drop_table("beneficiaries")
    op.drop_table("volunteer_function")
    op.drop_table("security_user_groups")
    op.drop_table("security_group_permissions")
    op.drop_index(
        op.f("ix_recruitment_submissions_user_id"), table_name="recruitment_submissions"
    )
    op.drop_index(
        op.f("ix_recruitment_submissions_status"), table_name="recruitment_submissions"
    )
    op.drop_index(
        op.f("ix_recruitment_submissions_full_name"),
        table_name="recruitment_submissions",
    )
    op.drop_index(
        op.f("ix_recruitment_submissions_email"), table_name="recruitment_submissions"
    )
    op.drop_table("recruitment_submissions")
    op.drop_index(op.f("ix_groups_system_key"), table_name="groups")
    op.drop_index(op.f("ix_groups_name"), table_name="groups")
    op.drop_table("groups")
    op.drop_index(
        op.f("ix_departure_interviews_volunteer_id"), table_name="departure_interviews"
    )
    op.drop_index(
        op.f("ix_departure_interviews_departure_date"),
        table_name="departure_interviews",
    )
    op.drop_table("departure_interviews")
    op.drop_index(
        op.f("ix_department_members_volunteer_id"), table_name="department_members"
    )
    op.drop_index(
        op.f("ix_department_members_department_id"), table_name="department_members"
    )
    op.drop_table("department_members")
    op.drop_index(
        op.f("ix_department_inventory_items_name"),
        table_name="department_inventory_items",
    )
    op.drop_index(
        op.f("ix_department_inventory_items_department_id"),
        table_name="department_inventory_items",
    )
    op.drop_index(
        op.f("ix_department_inventory_items_borrowed_by_volunteer_id"),
        table_name="department_inventory_items",
    )
    op.drop_table("department_inventory_items")
    op.drop_table("calendar_feed_tokens")
    op.drop_index(op.f("ix_calendar_events_visibility"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_title"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_status"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_author_id"), table_name="calendar_events")
    op.drop_table("calendar_events")
    op.drop_index(op.f("ix_bug_reports_status"), table_name="bug_reports")
    op.drop_index(op.f("ix_bug_reports_reporter_id"), table_name="bug_reports")
    op.drop_table("bug_reports")
    op.drop_index(op.f("ix_volunteers_full_name"), table_name="volunteers")
    op.drop_index(op.f("ix_volunteers_email"), table_name="volunteers")
    op.drop_table("volunteers")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_security_permissions_code"), table_name="security_permissions"
    )
    op.drop_index(
        op.f("ix_security_permissions_category"), table_name="security_permissions"
    )
    op.drop_table("security_permissions")
    op.drop_index(op.f("ix_security_groups_system_key"), table_name="security_groups")
    op.drop_index(op.f("ix_security_groups_name"), table_name="security_groups")
    op.drop_table("security_groups")
    op.drop_index(
        op.f("ix_recruitment_fields_position"), table_name="recruitment_fields"
    )
    op.drop_index(op.f("ix_recruitment_fields_key"), table_name="recruitment_fields")
    op.drop_table("recruitment_fields")
    op.drop_index(op.f("ix_functions_system_key"), table_name="functions")
    op.drop_index(op.f("ix_functions_name"), table_name="functions")
    op.drop_table("functions")
    op.drop_index(op.f("ix_departure_fields_position"), table_name="departure_fields")
    op.drop_index(op.f("ix_departure_fields_key"), table_name="departure_fields")
    op.drop_table("departure_fields")
    op.drop_index(op.f("ix_departments_system_key"), table_name="departments")
    op.drop_index(op.f("ix_departments_name"), table_name="departments")
    op.drop_table("departments")
    op.drop_index(
        op.f("ix_beneficiary_recruitment_fields_position"),
        table_name="beneficiary_recruitment_fields",
    )
    op.drop_index(
        op.f("ix_beneficiary_recruitment_fields_key"),
        table_name="beneficiary_recruitment_fields",
    )
    op.drop_table("beneficiary_recruitment_fields")
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS audit_events_append_only ON audit_events")
        op.execute("DROP FUNCTION IF EXISTS prevent_audit_event_mutation()")
    op.drop_index("idx_audit_entity", table_name="audit_events")
    op.drop_index("idx_audit_context", table_name="audit_events")
    op.drop_index(
        "idx_audit_changes_gin", table_name="audit_events", postgresql_using="gin"
    )
    op.drop_index("idx_audit_actor", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
