"""baseline current schema

Revision ID: 1d79afa0041b
Revises:
Create Date: 2026-06-30 21:08:13.254824+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d79afa0041b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "functions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_functions_name"), "functions", ["name"], unique=True)
    op.create_table(
        "recruitment_fields",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=250), nullable=False),
        sa.Column("field_type", sa.String(length=30), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("placeholder", sa.String(length=250), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recruitment_fields_key"), "recruitment_fields", ["key"], unique=True
    )
    op.create_index(
        op.f("ix_recruitment_fields_position"),
        "recruitment_fields",
        ["position"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=150), nullable=False),
        sa.Column("last_name", sa.String(length=150), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "volunteers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("social_link", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("join_date", sa.DateTime(), nullable=False),
        sa.Column("notes", sa.String(), nullable=False),
        sa.Column("history", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_volunteers_email"), "volunteers", ["email"], unique=True)
    op.create_index(
        op.f("ix_volunteers_full_name"), "volunteers", ["full_name"], unique=False
    )
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("leader_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["leader_id"], ["volunteers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_groups_name"), "groups", ["name"], unique=False)
    op.create_table(
        "recruitment_submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("social_link", sa.String(length=500), nullable=False),
        sa.Column("availability", sa.Text(), nullable=False),
        sa.Column("answers", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("return_reason", sa.Text(), nullable=True),
        sa.Column("decision_comment", sa.Text(), nullable=True),
        sa.Column("volunteer_id", sa.Integer(), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status_changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["volunteer_id"], ["volunteers.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("volunteer_id"),
    )
    op.create_index(
        op.f("ix_recruitment_submissions_email"),
        "recruitment_submissions",
        ["email"],
        unique=True,
    )
    op.create_index(
        op.f("ix_recruitment_submissions_full_name"),
        "recruitment_submissions",
        ["full_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recruitment_submissions_status"),
        "recruitment_submissions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recruitment_submissions_user_id"),
        "recruitment_submissions",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "volunteer_function",
        sa.Column("volunteer_id", sa.Integer(), nullable=False),
        sa.Column("function_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["function_id"], ["functions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["volunteer_id"], ["volunteers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("volunteer_id", "function_id"),
    )
    op.create_table(
        "beneficiaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("family_phone", sa.String(length=20), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("bo_enrolled", sa.Boolean(), nullable=False),
        sa.Column("last_priest_visit", sa.Date(), nullable=True),
        sa.Column("last_volunteer_meeting", sa.Date(), nullable=True),
        sa.Column("history", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_beneficiaries_full_name"), "beneficiaries", ["full_name"], unique=False
    )
    op.create_table(
        "group_volunteer",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("volunteer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["volunteer_id"], ["volunteers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("group_id", "volunteer_id"),
    )
    op.create_table(
        "attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("context", sa.String(length=50), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("beneficiary_id", sa.Integer(), nullable=True),
        sa.Column("volunteer_id", sa.Integer(), nullable=True),
        sa.Column("period", sa.String(length=7), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_backend", sa.String(length=50), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=127), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_by_username", sa.String(length=150), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_username", sa.String(length=150), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["beneficiary_id"], ["beneficiaries.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["volunteer_id"], ["volunteers.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attachments_beneficiary_id"),
        "attachments",
        ["beneficiary_id"],
        unique=False,
    )
    op.create_index(
        "ix_attachments_bo_card_lookup",
        "attachments",
        ["context", "group_id", "beneficiary_id", "volunteer_id", "period"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attachments_context"), "attachments", ["context"], unique=False
    )
    op.create_index(
        op.f("ix_attachments_group_id"), "attachments", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_attachments_period"), "attachments", ["period"], unique=False
    )
    op.create_index(
        op.f("ix_attachments_storage_key"), "attachments", ["storage_key"], unique=True
    )
    op.create_index(
        op.f("ix_attachments_volunteer_id"),
        "attachments",
        ["volunteer_id"],
        unique=False,
    )
    op.create_table(
        "beneficiary_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("beneficiary_id", sa.Integer(), nullable=False),
        sa.Column("volunteer_id", sa.Integer(), nullable=False),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.Column("additional_info", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["beneficiary_id"], ["beneficiaries.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["volunteer_id"], ["volunteers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "beneficiary_id", "volunteer_id", name="uq_beneficiary_volunteer"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("beneficiary_assignments")
    op.drop_index(op.f("ix_attachments_volunteer_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_storage_key"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_period"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_group_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_context"), table_name="attachments")
    op.drop_index("ix_attachments_bo_card_lookup", table_name="attachments")
    op.drop_index(op.f("ix_attachments_beneficiary_id"), table_name="attachments")
    op.drop_table("attachments")
    op.drop_table("group_volunteer")
    op.drop_index(op.f("ix_beneficiaries_full_name"), table_name="beneficiaries")
    op.drop_table("beneficiaries")
    op.drop_table("volunteer_function")
    op.drop_index(
        op.f("ix_recruitment_submissions_user_id"), table_name="recruitment_submissions"
    )
    op.drop_index(
        op.f("ix_recruitment_submissions_status"), table_name="recruitment_submissions"
    )
    op.drop_index(
        op.f("ix_recruitment_submissions_full_name"),
        table_name="recruitment_submissions",
    )
    op.drop_index(
        op.f("ix_recruitment_submissions_email"), table_name="recruitment_submissions"
    )
    op.drop_table("recruitment_submissions")
    op.drop_index(op.f("ix_groups_name"), table_name="groups")
    op.drop_table("groups")
    op.drop_index(op.f("ix_volunteers_full_name"), table_name="volunteers")
    op.drop_index(op.f("ix_volunteers_email"), table_name="volunteers")
    op.drop_table("volunteers")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_recruitment_fields_position"), table_name="recruitment_fields"
    )
    op.drop_index(op.f("ix_recruitment_fields_key"), table_name="recruitment_fields")
    op.drop_table("recruitment_fields")
    op.drop_index(op.f("ix_functions_name"), table_name="functions")
    op.drop_table("functions")
    # ### end Alembic commands ###
