"""Init revision

Revision ID: 3a853d2d6c75
Revises: 
Create Date: 2026-06-19 09:00:14.844300+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a853d2d6c75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_roles_name'), 'roles', ['name'], unique=True, schema='public')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_users_email'), 'users', ['email'], unique=True, schema='public')
    op.create_index(op.f('ix_public_users_username'), 'users', ['username'], unique=True, schema='public')
    op.create_table('volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('social_link', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('history', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['public.roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_volunteers_email'), 'volunteers', ['email'], unique=True, schema='public')
    op.create_index(op.f('ix_public_volunteers_full_name'), 'volunteers', ['full_name'], unique=False, schema='public')
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['public.volunteers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_groups_name'), 'groups', ['name'], unique=False, schema='public')
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('family_phone', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('bo_enrolled', sa.Boolean(), nullable=False),
    sa.Column('last_priest_visit', sa.Date(), nullable=True),
    sa.Column('last_volunteer_meeting', sa.Date(), nullable=True),
    sa.Column('history', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['public.groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_beneficiaries_full_name'), 'beneficiaries', ['full_name'], unique=False, schema='public')
    op.create_table('group_volunteer',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['public.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['public.volunteers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'volunteer_id'),
    schema='public'
    )
    op.create_table('beneficiary_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('additional_info', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['public.beneficiaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['public.volunteers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beneficiary_id', 'volunteer_id', name='uq_beneficiary_volunteer'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beneficiary_assignments', schema='public')
    op.drop_table('group_volunteer', schema='public')
    op.drop_index(op.f('ix_public_beneficiaries_full_name'), table_name='beneficiaries', schema='public')
    op.drop_table('beneficiaries', schema='public')
    op.drop_index(op.f('ix_public_groups_name'), table_name='groups', schema='public')
    op.drop_table('groups', schema='public')
    op.drop_index(op.f('ix_public_volunteers_full_name'), table_name='volunteers', schema='public')
    op.drop_index(op.f('ix_public_volunteers_email'), table_name='volunteers', schema='public')
    op.drop_table('volunteers', schema='public')
    op.drop_index(op.f('ix_public_users_username'), table_name='users', schema='public')
    op.drop_index(op.f('ix_public_users_email'), table_name='users', schema='public')
    op.drop_table('users', schema='public')
    op.drop_index(op.f('ix_public_roles_name'), table_name='roles', schema='public')
    op.drop_table('roles', schema='public')
    # ### end Alembic commands ###
